name: "Create Release and Upload Extension"

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Package Extension
        run: |
          cd apps/extension
          pnpm build
          pnpm package

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: apps/extension/build/chrome-mv3-prod.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
