name: "Create Release and Upload Extension"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build and Package Extension
        run: |
          cd apps/extension
          pnpm build
          pnpm package
          echo "Listing build directory contents:"
          ls -R build/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: apps/extension/build/chrome-mv3-prod.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
